name: Nightly build

on:
  push:
    branches:
      - "dev"
    paths:
      - "**.py"

jobs:
  test:
    name: Python tests and checks
    uses: ./.github/workflows/sub_testing.yml

  build-n-publish:
    name: Build and publish Python 🐍 distributions to TestPyPI 📦
    runs-on: ubuntu-latest
    environment: nightly
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    needs: test
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install --user build
      - name: Cleaning
        run : python setup.py clean
      - name: Build Exegol
        run: python -m build --sdist --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
